<html><head></head><body><div id="sbo-rt-content"><h2 class="h2" id="ch05"><span epub:type="pagebreak" id="page_45"/><strong><span class="big">5</span><br/>MODELING ASSEMBLIES</strong></h2>&#13;
<div class="image1"><img src="Images/common.jpg" alt="Images" width="246" height="245"/></div>&#13;
<p class="noindent">At some point, you’ll get bored of modeling designs that consist of a single part. In this chapter, you’ll learn how to use Fusion 360 to create more complex and multipart mechanisms, called <em>assemblies,</em> which can be made up of two or more <em>components</em> (parts) or even multiple subassemblies. A car’s engine is an example of an assembly.</p>&#13;
<p class="indent">Fusion 360 offers a few ways to create assemblies. You can make and assemble multiple solid bodies within a single Fusion 360 file. You can also combine separate files to form an assembly. In this chapter, you’ll learn both methods as well as how to combine them.</p>&#13;
<p class="indent">The method you use depends on what you’re trying to accomplish, as well as what makes the most sense to you on an intuitive level. For some people, having each file consist of a single solid body (one component) <span epub:type="pagebreak" id="page_46"/>seems like the most natural way to structure things. Others prefer to have a single file that contains all of the solid bodies—converted into components—for their assemblies. Using a single file may be simpler, but it provides less flexibility. Unless you have a good reason not to, keep components as separate files, because doing so makes the components easier to edit and helps with organization and collaboration.</p>&#13;
<p class="indent">In this chapter, you’ll also learn about reference geometry, an invaluable tool for creating complex models and the relationships within those models, which is necessary for advanced modeling.</p>&#13;
<h3 class="h3" id="ch00lev1sec51"><strong>Converting Solid Bodies into Components Within a Single File</strong></h3>&#13;
<p class="noindent">Components allow you to build assemblies in the same file as you build your bodies. Classically, most CAD software packages force a user to work on parts and assemblies in separate files; you’d choose between a part file or an assembly file. Fusion 360 does not explicitly differentiate between file types, so you can edit both parts and assemblies in the same file. Users create and manipulate bodies within components, which maintain their own coordinate systems and can be created in either the same file or separate files.</p>&#13;
<p class="indent">Here are some common user interface terms:</p>&#13;
<p class="hang"><strong>Joint</strong> A physical relationship between components.</p>&#13;
<p class="hang"><strong>Component</strong> Holds local coordinate system, bodies, features, and sketches.</p>&#13;
<p class="hang"><strong>Body</strong> Holds geometry with a type of construction.</p>&#13;
<p class="hang"><strong>Feature</strong> An action on a design and the parameters of that action.</p>&#13;
<p class="hang"><strong>Parameter</strong> A named value. Designs are recalculated when a parameter is altered.</p>&#13;
<p class="indentt">I’ll begin by showing you how to create and assemble components within one Fusion 360 file. Going this route has two primary benefits. First, since you’ll store all the parts in one file, they are easy to keep track of. Second, by splitting a single solid body into two, you can ensure an exact fit between components.</p>&#13;
<p class="indent">To learn this technique, you’ll model a box with a lid, which together form an assembly. Begin by opening a new file and modeling a rectangular prism that is 100 mm wide, 75 mm deep, and 50 mm tall. For a little panache, go ahead and add 5 mm fillets to all of the edges except the bottom four (see <a href="ch05.xhtml#ch05fig1">Figure 5-1</a>).</p>&#13;
<p class="indent">To turn this object into a box and a lid, you need to divide it into two pieces. You can do this easily with the Split Body tool. First, though, you need a way to define where that split is going to happen.</p>&#13;
<div class="image"><span epub:type="pagebreak" id="page_47"/><a id="ch05fig1"/><img src="Images/05fig01.jpg" alt="Images" width="926" height="579"/></div>&#13;
<p class="figcap"><em>Figure 5-1: Start by modeling a 100 mm × 75 mm × 50 mm rectangular prism.</em></p>&#13;
<h4 class="h4" id="ch00lev1sec52"><strong><em>Splitting an Object Using a Construction Plane</em></strong></h4>&#13;
<p class="noindent">One way to tell the Split Body tool where to cut is to sketch a simple line across the front or side face. This method is particularly useful when the split isn’t a straight line. You could, for instance, split a model along an arc.</p>&#13;
<p class="indent">Because we just want a simple straight cut, we’ll use a faster method: cutting along a <em>construction plane</em>. Construction planes, axes, and points are all examples of reference geometry. (Reference geometry is used during the modeling process as a guide, but it isn’t a physical part of the model.) You might use a construction plane to mirror a feature from one side of the model to the other, or you might use a construction axis as the axis of revolution for a Revolve feature.</p>&#13;
<p class="indent">In this case, you’ll create a construction plane, which tells the Split Body tool where to divide the solid body. Choose <strong>Offset Plane</strong> from the Construct drop-down menu. The Offset Plane tool creates a construction plane parallel to an existing plane of your choosing. In the “plane” box, select the top face of the box. Next, in the “distance” box of the drop-down menu, decide how far the new plane should be from the old plane. A positive value creates the new plane above the original one, whereas a negative value creates it below. For our purposes, enter <strong>–15.00 mm</strong>, as shown in <a href="ch05.xhtml#ch05fig2">Figure 5-2</a>.</p>&#13;
<p class="indent">Now you have everything you need to divide the model into two solid bodies. Select the <strong>Split Body</strong> tool from the Modify drop-down menu. When the tool asks you which body to split, you can click anywhere on the model. It will also ask what to use as the splitting tool, or the place where you want to separate the model. In this case, the splitting tool is the construction plane you just created (but it could also be a sketch or other reference). Select the construction plane and then finish the split, as shown in <a href="ch05.xhtml#ch05fig3">Figure 5-3</a>.</p>&#13;
<div class="image"><span epub:type="pagebreak" id="page_48"/><a id="ch05fig2"/><img src="Images/05fig02.jpg" alt="Images" width="894" height="717"/></div>&#13;
<p class="figcap"><em>Figure 5-2: Use Offset Plane to create a construction plane 15 mm below the top face.</em></p>&#13;
<div class="image"><a id="ch05fig3"/><img src="Images/05fig03.jpg" alt="Images" width="893" height="717"/></div>&#13;
<p class="figcap"><em>Figure 5-3: The Split Body tool uses a reference to divide a model into multiple solid bodies.</em></p>&#13;
<p class="indent"><span epub:type="pagebreak" id="page_49"/>Your model now consists of two separate solid bodies (one for the box and one for the lid). You no longer need the reference plane, so you can hide it by clicking the corresponding light bulb icon in the <strong>Construction</strong> section of the Component Browser (on the left). However, <em>do not</em> delete the construction plane because the Split Body feature is based on it. If the plane were deleted, any feature that depends on it would be invalidated, including the split body you just made.</p>&#13;
<h4 class="h4" id="ch00lev1sec53"><strong><em>Creating Components</em></strong></h4>&#13;
<p class="noindent">Although the two bodies in our model are split, they’re not yet defined as components. To convert all of the bodies into components at once (see <a href="ch05.xhtml#ch05fig4">Figure 5-4</a>), right-click <strong>Bodies</strong> in the Component Browser and choose <strong>Create Components from Bodies</strong>. You could also do this by right-clicking each body individually.</p>&#13;
<div class="image"><a id="ch05fig4"/><img src="Images/05fig04.jpg" alt="Images" width="834" height="797"/></div>&#13;
<p class="figcap"><em>Figure 5-4: All of the bodies can be converted into components in a single step.</em></p>&#13;
<p class="indent">The Component Browser should now have two components listed: the lid and the box. If you click the drop-down arrow for each of these, you should see that each component now has its own origin, planes, and bodies. You’ve effectively put two independent models within the same file. You can move each individually while still retaining the original coordinates of each.</p>&#13;
<h4 class="h4" id="ch00lev1sec54"><strong><em><span epub:type="pagebreak" id="page_50"/>Hollowing Out the Box and Creating a Lip</em></strong></h4>&#13;
<p class="noindent">Right now, each component is solid, but to store anything in the box, you need to make it hollow, as shown in <a href="ch05.xhtml#ch05fig5">Figure 5-5</a>. You already know how to do this with the Shell tool, so give the box a shell thickness of 3 mm and the lid a thickness of 6 mm. To work on each component individually, hover over it in the Component Browser and click <strong>Activate Component</strong>. To edit both components at once, hover over the top level of the Component Browser and select Activate Component.</p>&#13;
<div class="image"><a id="ch05fig5"/><img src="Images/05fig05.jpg" alt="Images" width="926" height="743"/></div>&#13;
<p class="figcap"><em>Figure 5-5: Shell each Component to make them hollow.</em></p>&#13;
<p class="indent">The lid component should have a thicker shell than the box because you don’t want the lid to slide off when you close the box. To keep it from doing that, you’ll need to give the lid a lip that fits into the bottom box. Using a thicker shell provides extra material to make that lip. Activate the lid component and rotate it so you can see the inside, then create a sketch on the bottom face (where the lip will be). Next, offset the outside edge by 3.5 mm and extrude the <em>inside profile</em> by 2.5 mm, as shown in <a href="ch05.xhtml#ch05fig6">Figure 5-6</a>.</p>&#13;
<div class="image"><span epub:type="pagebreak" id="page_51"/><a id="ch05fig6"/><img src="Images/05fig06.jpg" alt="Images" width="926" height="747"/></div>&#13;
<p class="figcap"><em>Figure 5-6: A cross-section view showing the extruded lip on the lid component</em></p>&#13;
<p class="indent">You should leave a 0.5 mm gap between the edge of the lip and the box, because when you’re designing parts that mate together, it’s important to think about how they’ll actually fit in the real world. If these two parts were modeled to have zero gap, then the actual objects might fit together too tightly (or not at all). In engineering terms, the room you allow for some error is called <em>tolerance</em>. This 0.5 mm tolerance helps ensure that the components will fit together, even if they aren’t manufactured perfectly.</p>&#13;
<p class="indent">How much tolerance to give your mating parts is a bit tricky. If you want the parts to fit together snugly, you might not give them any extra tolerance at all. If they need to be able to move freely, you might give them a lot. Determining the exact amount takes experience, trial and error, and knowledge of what you can expect from the fabrication techniques and materials used to make the part. High-quality machining can be very precise, so it’s usually safe to use a very tight tolerance in those cases. However, 3D printing is inherently imprecise (particularly hobbyist fused-filament fabrication printing), so loose tolerances are more appropriate there.</p>&#13;
<h4 class="h4" id="ch00lev1sec55"><strong><em>Defining Relationships</em></strong></h4>&#13;
<p class="noindent">When building assemblies, you’ll usually want to create relationships between the components. For example, when modeling a piston and a cylinder, you need to explicitly state that the piston is centered in the cylinder. You also need to specify its orientation, as well as the distance it can travel in the cylinder.</p>&#13;
<p class="indent"><span epub:type="pagebreak" id="page_52"/>To define the box’s relationship to the lid, you’ll first need to <em>ground</em> one of the components. This should lock that component in space, allowing the other components to move in relation to it. Generally, you’ll ground whichever component you think of as “the base.” Right-click the box component and click <strong>Ground</strong>.</p>&#13;
<p class="indent">Next, you’ll use joints to define the motion of the lid in relation to the box. Joints either restrict or allow a certain kinds of movement; that piston in the cylinder from the previous example would use a cylindrical joint to allow movement along the central axis, but not perpendicular to it.</p>&#13;
<p class="indent">To allow our box to open and close, let’s keep the lid centered on the box while still allowing it to move up and down.</p>&#13;
<p class="indent">From the Assemble drop-down menu, select <strong>Joint</strong> (or use the <strong>J</strong> shortcut). Next, choose a component and a reference point on that component. Usually, this is part of a face or a centerpoint. Select the centerpoint of the side faces of each component (see <a href="ch05.xhtml#ch05fig7">Figure 5-7</a>). Then, click <strong>Flip</strong>, if necessary, and choose <strong>Planar</strong> as the <strong>Motion Type</strong>.</p>&#13;
<div class="image"><a id="ch05fig7"/><img src="Images/05fig07.jpg" alt="Images" width="926" height="743"/></div>&#13;
<p class="figcap"><em>Figure 5-7: Add a planar joint to the side faces of the components.</em></p>&#13;
<p class="indent">Repeat this process to add a second planar joint to the front faces. Now you should be able to move the lid freely up and down, but not side to side or front to back.</p>&#13;
<p class="indent">Your first assembly is finished! If you want, you can export each component as an STL file and 3D print your own box using this model.</p>&#13;
<h3 class="h3" id="ch00lev1sec56"><span epub:type="pagebreak" id="page_53"/>Assembling Components from External Files</h3>&#13;
<p class="noindent">While you could model and assemble all of your parts in a single file, as you did for the box, it can be useful to separate the components into their own files. Here are a few reasons why:</p>&#13;
<ul>&#13;
<li class="noindent">When you’re working with very large assemblies consisting of many parts, it makes keeping the components organized easier and keeps file sizes manageable.</li>&#13;
<li class="noindent">It allows you to collaborate with others so that each member of an engineering team could work on a different component of the assembly simultaneously.</li>&#13;
<li class="noindent">Most assemblies have duplicate parts. If you were designing a car, you wouldn’t want to model every M5X100 machine screw individually. Instead, you’d want to model one screw and drop as many instances as you needed into your final assembly file.</li>&#13;
</ul>&#13;
<p class="indent">To learn how to create assemblies from separate files, we’ll create a door hinge with two identical sides. You’ll create a single model and import two copies of it into an assembly file to complete the hinge.</p>&#13;
<h4 class="h4" id="ch00lev1sec57"><strong><em>Making the Hinge Barrel and Mount</em></strong></h4>&#13;
<p class="noindent">Let’s start by making the barrel of the hinge. This should be a hollow cylinder, with the sketch on the top plane, extruded symmetrically. Make the outer diameter (OD) 12 mm, the inner diameter (ID) 8 mm, and the total length 100 mm, as shown in <a href="ch05.xhtml#ch05fig8">Figure 5-8</a>.</p>&#13;
<div class="image"><a id="ch05fig8"/><img src="Images/05fig08.jpg" alt="Images" width="806" height="647"/></div>&#13;
<p class="figcap"><em>Figure 5-8: Extrude a cylinder with the following dimensions: 12 mm OD, 8 mm ID, 100 mm long.</em></p>&#13;
<p class="indent"><span epub:type="pagebreak" id="page_54"/>Next, create a flat face for the hinge mount. Start by sketching on one of the end faces of the cylinder. Move away from the cylinder and complete three sides of a rectangle that is 56 mm long and 3 mm wide.</p>&#13;
<p class="indent">There is no need to trim the overlapping lines—they won’t hurt anything if you leave them like you see in <a href="ch05.xhtml#ch05fig9">Figure 5-9</a>. If we were actually producing this hinge, we’d want to give it some space for tolerance. But, for the sake of simplicity, you can just align one line with the centerpoint of the barrel.</p>&#13;
<div class="image"><a id="ch05fig9"/><img src="Images/05fig09.jpg" alt="Images" width="927" height="743"/></div>&#13;
<p class="figcap"><em>Figure 5-9: Sketch a plane to create a flat face for the hinge mount. Overlapping lines aren’t a problem; you can just extrude the closed loop profile.</em></p>&#13;
<p class="indent">Once your sketch looks like <a href="ch05.xhtml#ch05fig9">Figure 5-9</a>, select the rectangular region and extrude it to the other end of the barrel. Your model should now look like <a href="ch05.xhtml#ch05fig10">Figure 5-10</a>. The next step is to cut out portions of the barrel.</p>&#13;
<div class="image"><span epub:type="pagebreak" id="page_55"/><a id="ch05fig10"/><img src="Images/05fig10.jpg" alt="Images" width="926" height="743"/></div>&#13;
<p class="figcap"><em>Figure 5-10: Extrude the rest of the hinge body.</em></p>&#13;
<h4 class="h4" id="ch00lev1sec58"><strong><em>Cutting Out the Barrel and Changing Parameters</em></strong></h4>&#13;
<p class="noindent">We’ll put two gaps in the cylinder so the halves will fit together like puzzle pieces. Each gap must be 25 mm long (the length of the cylinder divided by 4), 12 mm wide (the OD of the barrel), and 50 mm from the flat edge opposite the barrel. Draw and extrude two rectangles with those dimensions to divide the barrel into four equal sections, as shown in <a href="ch05.xhtml#ch05fig11">Figure 5-11</a>.</p>&#13;
<p class="indent">But wait! What happens if the original dimensions change? If, for instance, you alter the diameter of the barrel, the sections you just created will no longer be to scale. This is where you can take advantage of the power of parametric modeling by reusing the dimensions you’ve already specified.</p>&#13;
<p class="indent">Go back and edit the sketch you just created. Then, open up the <strong>Change Parameters</strong> dialog from the Modify drop-down menu. Under the Model Parameters tab, shown in <a href="ch05.xhtml#ch05fig12">Figure 5-12</a>, you’ll see entries for each feature you’ve created. If you expand those entries, you’ll be given a list of all the dimensions used to create that feature, as well as the names of those dimensions.</p>&#13;
<div class="image"><span epub:type="pagebreak" id="page_56"/><a id="ch05fig11"/><img src="Images/05fig11.jpg" alt="Images" width="909" height="729"/></div>&#13;
<p class="figcap"><em>Figure 5-11: Divide the barrel into four 25 mm sections.</em></p>&#13;
<div class="image"><a id="ch05fig12"/><img src="Images/05fig12.jpg" alt="Images" width="662" height="502"/></div>&#13;
<p class="figcap"><em>Figure 5-12: The Parameters dialog lists all the dimensions you’ve used in earlier features.</em></p>&#13;
<p class="indent"><span epub:type="pagebreak" id="page_57"/>Now you can change certain dimensions so they reference previous features by replacing the numerical entries with values that depend on the dimensions of other objects. For example, because the length of the barrel is named “d3,” you can change the expression for the length of the rectangles to “d3 / 4” to make sure they will always measure a quarter of the barrel’s length.</p>&#13;
<p class="indent">At this point, your hinge should look like the one shown in <a href="ch05.xhtml#ch05fig13">Figure 5-13</a>.</p>&#13;
<div class="image"><a id="ch05fig13"/><img src="Images/05fig13.jpg" alt="Images" width="521" height="473"/></div>&#13;
<p class="figcap"><em>Figure 5-13: The solid should look like this after your cuts are extruded.</em></p>&#13;
<p class="indent">Now we just need to create the mounting holes.</p>&#13;
<h4 class="h4" id="ch00lev1sec59"><strong><em>Using the Hole Tool</em></strong></h4>&#13;
<p class="noindent">The final step of the modeling process is to give the flat plate some mounting holes, where the screws will go. This step isn’t actually important to this tutorial, but it’s good to get into the habit of adding details.</p>&#13;
<p class="indent">You could put these holes in however you like, but I’d recommend a method we haven’t used yet: the <em>Hole</em> tool. For the hinge to work, the screw heads need to be flush with the surface of the flat plate. This means you’ll have to make countersunk holes. Add some sketch points where you think the holes should be on the <em>inside</em> face of the hinge. Use constraints or parameter references to place these. This way, their placements will update if the hinge dimensions change.</p>&#13;
<p class="indent">Finish the sketch and choose the Hole tool from the Create drop-down menu. Select each of the points you just sketched. Change the <strong>Hole Type</strong> setting to <strong>Countersink</strong> and then explore the rest of the settings to get a feel for what they do. Finalize the feature when you think it looks like the mounting holes on a hinge should (see <a href="ch05.xhtml#ch05fig14">Figure 5-14</a>).</p>&#13;
<div class="image"><span epub:type="pagebreak" id="page_58"/><a id="ch05fig14"/><img src="Images/05fig14.jpg" alt="Images" width="927" height="743"/></div>&#13;
<p class="figcap"><em>Figure 5-14: The final product should look roughly like this.</em></p>&#13;
<p class="indent">Go ahead and save this file as something like <em>HingeHalf</em>. Then open a new document and save it as <em>HingeAssembly</em>.</p>&#13;
<p class="indent">When you’re in the blank <em>HingeAssembly</em> file, open the Project Browser using the Data Panel button at the top left of the Fusion 360 window. Right-click the <em>HingeHalf</em> model and choose the <strong>Insert into Current Design</strong> option. Click <strong>OK</strong> in the dialog to place the component anywhere within the <em>HingeAssembly</em> document’s space. Then repeat this process to insert another copy of the <em>HingeHalf</em> model.</p>&#13;
<p class="indent">Now you can assemble the halves, just like you did in the first part of this chapter. Choose one of the halves to be the ground model and use joints to put the two together, as shown in <a href="ch05.xhtml#ch05fig15">Figure 5-15</a>. One joint should be cylindrical and the other planar.</p>&#13;
<div class="image"><span epub:type="pagebreak" id="page_59"/><a id="ch05fig15"/><img src="Images/05fig15.jpg" alt="Images" width="926" height="743"/></div>&#13;
<p class="figcap"><em>Figure 5-15: Add joints to the assembly so the hinge can open and close.</em></p>&#13;
<p class="indent">This should allow your hinge to open and close while staying together.</p>&#13;
<h3 class="h3" id="ch00lev1sec60"><strong>Combining Assembly Methods</strong></h3>&#13;
<p class="noindent">As you can see, both ways of creating an assembly have their benefits. Working within a single file makes it possible to derive several parts from a single base object, whereas creating an assembly from multiple files can save you the trouble of crafting duplicate objects. You can also combine these methods to get the best of both worlds. Let’s try this out now by adding a pin to the hinge assembly within the <em>HingeAssembly</em> file.</p>&#13;
<p class="indent">Make sure the top level of <em>HingeAssembly</em> is active in the Component Browser and then create a new component by right-clicking <em>HingeAssembly</em> (see <a href="ch05.xhtml#ch05fig16">Figure 5-16</a>).</p>&#13;
<p class="indent">Model the pin using the tools you’ve learned so far. Once it’s finished, reactivate the top level of <em>HingeAssembly</em> to add joints for the pin so that it looks like the model shown in <a href="ch05.xhtml#ch05fig16">Figure 5-16</a>.</p>&#13;
<div class="image"><span epub:type="pagebreak" id="page_60"/><a id="ch05fig16"/><img src="Images/05fig16.jpg" alt="Images" width="926" height="743"/></div>&#13;
<p class="figcap"><em>Figure 5-16: Add a pin to the assembly within the</em> HingeAssembly <em>file.</em></p>&#13;
<h3 class="h3" id="ch00lev1sec61"><strong>Summary</strong></h3>&#13;
<p class="noindent">Now that you know how to build assemblies, your projects are no longer constrained to a single part. You can create complex models that contain as many parts as you’d like.</p>&#13;
<p class="indent">In the coming chapters, instead of telling you which method to use to build assemblies, I’ll leave it up to you to choose how best to execute the project.</p>&#13;
</div>



  </body></html>